all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.211, mac: '1c:83:41:40:4b:f4', disk: nvme0, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.212, mac: '1c:83:41:40:52:a6', disk: nvme0, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.213, mac: '1c:83:41:40:50:a8', disk: nvme0, network_interface: eno1}
    workers:
      hosts:
